### PR TITLE
pipe: restore pipe size even if a pipe is empty

### LINKED ISSUE #995: zdtm/transition/fifo_loop fails by timeout
```
===================== Run zdtm/transition/fifo_loop in uns =====================
Start test
./fifo_loop --pidfile=fifo_loop.pid --outfile=fifo_loop.out --filename=fifo_loop.test
    PID TTY          TIME CMD
    170 ?        00:00:00 fifo_loop
    PID TTY      STAT   TIME COMMAND
      1 ?        S      0:03 python zdtm.py
      3 ?        S      0:00 python zdtm.py
    167 ?        Z      0:00  \_ [criu] <defunct>
    193 ?        R      0:00  \_ ps axf 170
    170 ?        Ss     0:00 ./fifo_loop --pidfile=fifo_loop.pid --outfile=fifo_loop.out --filename=fifo_loop.test
    185 ?        Ss     0:00  \_ ./fifo_loop --pidfile=fifo_loop.pid --outfile=fifo_loop.out --filename=fifo_loop.test
    186 ?        S      0:00      \_ ./fifo_loop --pidfile=fifo_loop.pid --outfile=fifo_loop.out --filename=fifo_loop.test
    187 ?        S      0:00      \_ ./fifo_loop --pidfile=fifo_loop.pid --outfile=fifo_loop.out --filename=fifo_loop.test
    188 ?        S      0:00      \_ ./fifo_loop --pidfile=fifo_loop.pid --outfile=fifo_loop.out --filename=fifo_loop.test
Run criu dump
Run criu lazy-pages
Run criu restore
Send the 15 signal to  170
Wait for zdtm/transition/fifo_loop(170) to die for 0.100000
Wait for zdtm/transition/fifo_loop(170) to die for 0.200000
Wait for zdtm/transition/fifo_loop(170) to die for 0.400000
Wait for zdtm/transition/fifo_loop(170) to die for 0.800000
Wait for zdtm/transition/fifo_loop(170) to die for 1.600000
Wait for zdtm/transition/fifo_loop(170) to die for 3.200000
Wait for zdtm/transition/fifo_loop(170) to die for 6.400000
Wait for zdtm/transition/fifo_loop(170) to die for 12.800000
Wait for zdtm/transition/fifo_loop(170) to die for 25.600000
##### Test zdtm/transition/fifo_loop FAIL at zdtm/transition/fifo_loop die #####
Send the 9 signal to  170
Wait for zdtm/transition/fifo_loop(170) to die for 0.100000
criu lazy-pages exited with 0
```

### PR DESCRIPTION
**Pull request by avagin**
Without this patch, pipe size is restored only if a pipe has queued data.

Fixes #995

Reported-by: Mr Jenkins

### CODE REVIEW

**Comment by avagin** [comment]
Here is explanation why it worked before and doesn't work now: https://lkml.org/lkml/2020/3/5/814

File: criu/pipes.c [hunk 1]
```diff
@@ -212,9 +212,9 @@ int restore_pipe_data(int img_type, int pfd, u32 id, struct pipe_data_rst **hash
 	munmap(pd->data, pd->pde->bytes);
 	pd->data = NULL;
 out:
-	ret = 0;
+	exit_code = 0;
 err:
-	return ret;
```
Comment (Snorch) [inline criu/pipes.c]: Initially we had this err label to close image fd on error path ed456a1b3 ("pipe: restore pipe data"). Now when we don't have to do it can we remove this excess label and put proper "return 0/-1" everywhere?

Comment (avagin) [reply criu/pipes.c]: Fixed

**Comment by rppt** [comment]
> Without this patch, pipe size is restored only if a pipe has queued data.
> 
> Fixes #995
> 
> Reported-by: Mr Jenkins
