### PR TITLE
bfd: loop through read()/write() when the action is incomplete

### LINKED ISSUE #1504: image streamer test fail
The following test sometimes fails with `Error (criu/image.c:694): Img trimmed 1048551/1048576` ([restore.log](https://github.com/checkpoint-restore/criu/files/6642277/restore.log)).

```
./test/zdtm.py run --stream -p2 -t zdtm/transition/fifo_loop
```
https://github.com/checkpoint-restore/criu/runs/2809666897

### PR DESCRIPTION
**Pull request by nviennot**
The callers of bread() and bwrite() assume the operation reads/writes
the complete length of the passed buffer.
We must loop when invoking the read()/write() APIs.

Fixes #1504

### CODE REVIEW

**Review by adrianreber — APPROVED** [review]
Thanks. Looks good. It fixes the error and sounds reasonable.

**Comment by adrianreber** [comment]
@checkpoint-restore/maintainers PTAL. This fixes one of the currently existing CI errors.

File: criu/util.c [hunk 1]
```diff
@@ -1583,4 +1583,38 @@ char *get_legacy_iptables_bin(bool ipv6)
...
+	return n;
+}
+
+ssize_t write_all(int fd, const void *buf, size_t size)
+{
+	ssize_t n = 0;
+	while (n < size) {
+		ssize_t ret = write(fd, buf, size - n);
+		if (ret == -1) {
+			if (errno == EINTR)
```
Comment (rst0git) [inline criu/util.c:1612]: In addition to `EINTR`, should we also check for `errno == EAGAIN`?

Comment (nviennot) [reply criu/util.c:1612]: So what happens when we've already made some progress, and then we get EAGAIN.

Should we return the number of bytes already written? in which case, this is not that better than the original write()

Should we return a EAGAIN? But then we've already written some content, and the caller will need to know about it. So that's bad. Can't do that.

In other words, if we can get EAGAIN, the caller is just better off using regular read()/write(). Which means that the read_all()/write_all() APIs are for blocking fds only.
In this case, if we get EAGAIN maybe it would be appropriate to return EINVAL? and add a comment on these functions that these APIs are for blocking fds only.
What do you think?

Comment (rst0git) [reply criu/util.c:1612]: >In this case, if we get EAGAIN maybe it would be appropriate to return EINVAL? and add a comment on these functions that these APIs are for blocking fds only.

Sounds good. read_all() and write_all() are generic functions and it would be good to keep them simple.

Comment (nviennot) [reply criu/util.c:1627]: I've updated the PR
