### PR TITLE
vdso: handle vvar_vclock vma-s

### LINKED ISSUE #2532: vdso: Unexpected rt vDSO area bounds
Today's Fedora rawhide updates broke checkpoint/restore in podman/criu. The error is triggered by the kernel and it has been bisected to the following package updates:

- works: kernel-core-6.13.0-0.rc0.20241119git158f238aa69d.2.fc42.x86_64
- fails: kernel-core-6.13.0-0.rc0.20241125git9f16d5e6f220.8.fc42.x86_64

**Reproducible:** Always

**Steps to Reproduce:**
- `podman run --name=test1 -d quay.io/libpod/busybox sleep 1000`
- `podman container checkpoint test1`

**Actual Results:**
```
2024-11-26T16:11:08.428787Z: CRIU checkpointing failed -52.  Please check CRIU logfile /var/lib/containers/storage/overlay-containers/2a3d740ede2eed92a3f963902dcb12bdd4e476ee2f3f73ffc86dfee71a5f9fbe/userdata/dump.log
Error: `/usr/bin/crun checkpoint --image-path /var/lib/containers/storage/overlay-containers/2a3d740ede2eed92a3f963902dcb12bdd4e476ee2f3f73ffc86dfee71a5f9fbe/userdata/checkpoint --work-path /var/lib/containers/storage/overlay-containers/2a3d740ede2eed92a3f963902dcb12bdd4e476ee2f3f73ffc86dfee71a5f9fbe/userdata 2a3d740ede2eed92a3f963902dcb12bdd4e476ee2f3f73ffc86dfee71a5f9fbe` failed: exit status 1
```

**Full [criu log](https://artifacts.dev.testing-farm.io/4ff7f22a-1bc3-4c0b-944c-ff705a67615d/work-podman-miscrmewa1yc/plans/cockpit-podman/podman-misc/execute/data/guest/default-0/test/browser/other-1/data/TestApplication-testCheckpointRestore-dump.log) ends like this:**

```
(00.019461) vdso: Parsing at 7f13e5a1e000 7f13e5a20000
(00.019479) vdso: PT_LOAD p_vaddr: 0
(00.019482) vdso: DT_HASH: 120
(00.019483) vdso: DT_STRTAB: 340
(00.019485) vdso: DT_SYMTAB: 1d8
(00.019486) vdso: DT_STRSZ: 9c
(00.019488) vdso: DT_SYMENT: 18
(00.019489) vdso: nbucket 3 nchain f bucket 7f13e5a1e128 chain 7f13e5a1e134
(00.019492) Error (criu/vdso.c:381): vdso: Unexpected rt vDSO area bounds
(00.019494) Error (criu/vdso.c:613): vdso: Failed to fill self vdso symtable
(00.019496) Error (criu/kerndat.c:1906): kerndat_vdso_fill_symtable failed when initializing kerndat.
(00.019588) Found mmap_min_addr 0x10000
(00.019668) files stat: fs/nr_open 1073741816
```

**Expected Results:** checkpointing works

*Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=2328985*

### PR DESCRIPTION
**Pull request by avagin**
The vvar_vclock was introduced by [1]. Basically, the old vvar vma has been splited on two parts. In term of C/R, these two vma-s can be still treated as one.

[1] e93d2521b27f ("x86/vdso: Split virtual clock pages into dedicated mapping")

Fixes #2532

### CODE REVIEW

File: criu/pie/parasite-vdso.c [hunk 1]
```diff
@@ -54,8 +55,19 @@ static int park_at(struct vdso_maps *rt, unsigned long vdso, unsigned long vvar)
 
 	std_log_set_gettimeofday(NULL); /* stop using vdso for timings */
 
-	if (vvar)
+	if (vvar) {
+		if (vvar_vclock_size) {
```
Comment (rst0git) [inline criu/pie/parasite-vdso.c:59]: @avagin Would it be possible to add a comment here is reference to the kernel commit?
`e93d2521b27f ("x86/vdso: Split virtual clock pages into dedicated mapping")`

**Comment by rst0git** [comment]
LGTM. I tested this patch with `6.13.0-0.rc1.20241204gitfeffde684ac2.17.fc42.x86_64` and confirmed that it fixes the error.

**Review by rst0git — APPROVED** [review]

**Review by mihalicyn — APPROVED** [review]

**Comment by avagin** [comment]
@t-8ch thank you for the head-up. The mailing list isn't used often these days and we didn't notice when it stopped working. We will fix it. Thanks a lot.
