### PR TITLE
compel: Fix ppc64le memory corruption near stack

### LINKED ISSUE #1946: ppc64le: blinky zdtm/transition/maps007
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
We have blinking `zdtm/transition/maps007` test

https://ci.kernoops.org/job/CRIU/view/CRIU-devel/job/CRIU-ppc64le/job/criu-dev/497/testReport/junit/(root)/criu/zdtm_transition_maps007/
https://ci.kernoops.org/job/CRIU/view/CRIU-devel/job/CRIU-ppc64le/job/criu-dev/495/testReport/junit/(root)/criu/zdtm_transition_maps007/
https://ci.kernoops.org/job/CRIU/view/CRIU-devel/job/CRIU-ppc64le/job/criu-dev/484/testReport/junit/(root)/criu/zdtm_transition_maps007/

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

**Additional environment details:**

### PR DESCRIPTION
**Pull request by ymanton**
I've been seeing intermittent crashes on ppc64le, tracked back to incorrect parasite stack setup. The ppc64le ABI allows functions to write to their caller's stack frame, so we have to allocate a dummy frame before running parasite code on the stack, otherwise function prologues may write past the end of stack memory. The s390x ABI has the same behaviour, but the code there does the right thing. Fixed the ppc64le code in the same way.

I've added a simple test case (copied & modified an existing compel test) that checks that memory after the stack buffer is not modified after the parasite is set up. (It only detects modification, not cases where the same value is written.)

Looked around existing issues; turns out #1946 is the same problem, crashes when the stack ends on a page boundary and the next page is not writable, otherwise memory is just silently corrupted.

Fixes #1946

### CODE REVIEW

**Comment by adrianreber** [comment]
@ymanton thanks for the PR. Thanks for including a test.

@mihalicyn can you test this on the Jenkins systems to see if it fixes the errors you have seen in #1946

@rst0git We talked about ppc64le problems just today, does this help?

@ldu4 In case you have some input/comments?

File: compel/test/stack/.gitignore [hunk 1]
```diff
@@ -0,0 +1,4 @@
+parasite.h
+parasite.po
```
Comment (Snorch) [inline compel/test/stack/.gitignore:2]: Do we also need parasite.o here?

File: compel/test/stack/spy.c [hunk 2]
```diff
@@ -0,0 +1,368 @@
...
+	i = 1;
+	if (write(p_in[1], &i, sizeof(i)) != sizeof(i))
+		return 1;
+	i = 42;
+	if (write(p_in[1], &i, sizeof(i)) != sizeof(i))
+		return 1;
+
+	printf("Checking the victim alive\n");
+	pass = chk(p_out[0], 1);
+	pass = chk(p_out[0], 42);
```
Comment (Snorch) [inline compel/test/stack/spy.c:322]: You may override previous chk fail result here, that looks like a bug.

File: compel/test/stack/spy.c [hunk 3]
```diff
@@ -0,0 +1,368 @@
...
+
+	printf("Checking the result\n");
+
+	/* These two came from parasite */
+	pass = chk(p_out[0], 138);
+	pass = chk(p_out[0], 403);
+
+	/* These two came from post-infect */
+	pass = chk(p_out[0], 1234);
+	pass = chk(p_out[0], 4096);
```
Comment (Snorch) [inline compel/test/stack/spy.c:360]: Same here, previous chk()-s can both pass and fail and test would not mention this.

File: compel/src/lib/infect.c [hunk 4]
```diff
@@ -968,6 +968,14 @@ static int compel_map_exchange(struct parasite_ctl *ctl, unsigned long size)
 }
 
 int compel_infect(struct parasite_ctl *ctl, unsigned long nr_threads, unsigned long args_size)
+{
+	if (compel_infect_no_daemon(ctl, nr_threads, args_size) || parasite_start_daemon(ctl))
```
[the remark this answers is not in the document]
Comment (ymanton) [reply compel/src/lib/infect.c]: Fixed both issues, thanks.

File: compel/test/stack/.gitignore (hunk 1 above)
Comment (ymanton) [reply compel/test/stack/.gitignore:2]: There's `*.o` in the root .gitignore that filters it out; these test specific .gitignore files look like they only mention additional things to ignore.

File: compel/test/stack/spy.c (hunk 2 above)
Comment (ymanton) [reply compel/test/stack/spy.c:324]: Thanks, it was present in the test I copied. Fixed in both places.

File: compel/test/stack/spy.c (hunk 3 above)
Comment (ymanton) [reply compel/test/stack/spy.c]: Fixed in both tests.

File: compel/test/stack/spy.c [hunk 5]
```diff
@@ -0,0 +1,368 @@
...
+	int ret = 0;
+
+	if (((uintptr_t)page & (page_size() - 1)) != 0) {
+		fprintf(stderr, "Page address not aligned\n");
+		ret = -1;
+		goto done;
+	}
+
+	char victim_maps_path[6 + 11 + 5 + 1];
+	int written = snprintf(victim_maps_path, sizeof(victim_maps_path), "/proc/%d/maps", pid);
```
Comment (Snorch) [inline compel/test/stack/spy.c:68]: Variable definition should be at the beginning of the function. And it is better to separate definition from the assignment, when second argument of the assignment is complex, e.g. involves function call.

File: compel/test/stack/spy.c [hunk 6]
```diff
@@ -0,0 +1,368 @@
...
+	free(maps_line);
+	fclose(maps);
+done:
+	return ret;
+}
+
+static void *read_proc_mem(int pid, void *offset, size_t len)
+{
+	char victim_mem_path[6 + 11 + 4 + 1];
+	int written = snprintf(victim_mem_path, sizeof(victim_mem_path), "/proc/%d/mem", pid);
```
Comment (Snorch) [inline compel/test/stack/spy.c:116]: Same, please do variable declaration separate from other code, and put empty line between variable declaration and other code.

File: compel/test/stack/spy.c [hunk 7]
```diff
@@ -0,0 +1,368 @@
...
+			return -1;
+		}
+	}
+	if (saved_size > 0) {
+		void *sd = read_proc_mem(pid, stack, saved_size);
+		if (sd == NULL)
+			return -1;
+		*saved_data = sd;
+	} else
+		*saved_data = NULL;
```
Comment (Snorch) [inline compel/test/stack/spy.c:171]: All branches of the if else statement should either have brackets simultaneously or don't have them simultaneously. The above is not allowed by codding style. https://www.kernel.org/doc/html/v4.10/process/coding-style.html#placing-braces-and-spaces

File: compel/test/stack/spy.c [hunk 8]
```diff
@@ -0,0 +1,368 @@
...
+	size_t page_mask = page_size() - 1;
+	size_t saved_size = 0;
+	size_t stack_size_last_page = (uintptr_t)stack & page_mask;
+	void *next_page = stack;
+	if (stack_size_last_page != 0) {
+		size_t empty_space_last_page = page_size() - stack_size_last_page;
+		saved_size = min(empty_space_last_page, (size_t)SAVED_DATA_MAX);
+		next_page += page_size() - stack_size_last_page;
+	}
+	while (saved_size < SAVED_DATA_MAX && next_page != NULL) {
```
Comment (Snorch) [inline compel/test/stack/spy.c:152]: Please separate logically separate code instances from each other by new lines, this way code would gain some more readability.

**Comment by rst0git** [comment]
> We talked about ppc64le problems just today, does this help?

The problem we have seen with ppc64le looks unrelated to this PR.

File: compel/test/stack/spy.c (hunk 5 above)
Comment (ymanton) [reply compel/test/stack/spy.c]: Fixed, thanks.

File: compel/test/stack/spy.c (hunk 6 above)
Comment (ymanton) [reply compel/test/stack/spy.c]: Fixed, thanks.

File: compel/test/stack/spy.c (hunk 7 above)
Comment (ymanton) [reply compel/test/stack/spy.c:194]: Fixed, thanks.

File: compel/test/stack/spy.c (hunk 8 above)
Comment (ymanton) [reply compel/test/stack/spy.c:170]: Fixed here and elsewhere, thanks.

File: compel/test/stack/spy.c [hunk 9]
```diff
@@ -0,0 +1,394 @@
...
+
+	if (((uintptr_t)page & (page_size() - 1)) != 0) {
+		fprintf(stderr, "Page address not aligned\n");
+		ret = -1;
+		goto done;
+	}
+
+	written = snprintf(victim_maps_path, sizeof(victim_maps_path), "/proc/%d/maps", pid);
+
+	if (written < 0 || written >= sizeof(victim_maps_path)) {
```
Comment (Snorch) [inline compel/test/stack/spy.c:71]: Look on other CRIU code, there is normally no newline between function call and its result checking, so this one looks excess.

File: compel/test/stack/spy.c [hunk 10]
```diff
@@ -0,0 +1,394 @@
...
+
+		default:
+			return -1;
+		}
+	}
+
+	if (saved_size > 0) {
+		void *sd = read_proc_mem(pid, stack, saved_size);
+
+		if (sd == NULL)
```
Comment (Snorch) [inline compel/test/stack/spy.c:189]: Again separate variable declaration and code please, like:
```
void *sd;

sd = read_proc_mem(pid, stack, saved_size);
if (sd == NULL)
```

File: compel/test/stack/spy.c [hunk 11]
```diff
@@ -0,0 +1,394 @@
...
+		next_page += page_size() - stack_size_last_page;
+	}
+
+	while (saved_size < SAVED_DATA_MAX && next_page != NULL) {
+		switch (page_writable(ctl, pid, next_page)) {
+		case 1:
+			saved_size = min((size_t)(saved_size + page_size()), (size_t)SAVED_DATA_MAX);
+			next_page += page_size();
+			break;
+
```
Comment (Snorch) [inline compel/test/stack/spy.c:176]: Newline between cases is not what we normally do in criu codebase, please remove.

File: compel/test/stack/spy.c (hunk 8 above)
Comment (Snorch) [reply compel/test/stack/spy.c:170]: I've commented some places where you've added to much newlines, others are good.

File: compel/test/infect/spy.c [hunk 12]
```diff
@@ -176,12 +178,10 @@ int main(int argc, char **argv)
...
 
 	/* These two came from parasite */
-	pass = chk(p_out[0], 138);
-	pass = chk(p_out[0], 403);
+	pass = chk(p_out[0], 138) && chk(p_out[0], 403);
 
 	/* These two came from post-infect */
-	pass = chk(p_out[0], 1234);
-	pass = chk(p_out[0], 4096);
+	pass = pass && chk(p_out[0], 1234) && chk(p_out[0], 4096);
```
Comment (Snorch) [inline compel/test/infect/spy.c:184]: May be shorter `pass &&= chk(p_out[0], 1234) && chk(p_out[0], 4096);` or even separate chk to different lines:
```
pass &&= chk(p_out[0], 1234);
pass &&= chk(p_out[0], 4096);
```

File: compel/test/stack/spy.c (hunk 10 above)
Comment (ymanton) [reply compel/test/stack/spy.c:188]: Fixed here and elsewhere, thanks.

File: compel/test/stack/spy.c (hunk 11 above)
Comment (ymanton) [reply compel/test/stack/spy.c]: Fixed, thanks.

File: compel/test/infect/spy.c (hunk 12 above)
Comment (ymanton) [reply compel/test/infect/spy.c:184]: Logical assignment operators don't exist in C.

(You were possibly thinking the bitwise `&=`?)

Comment (Snorch) [reply compel/test/infect/spy.c:184]: > Logical assignment operators don't exist in C.

Yes, my mistake =)

I'd then advise to reverse return of chk() as it is looks cleaner like this https://github.com/Snorch/criu/commit/6c3214445dec26c8f3f2faef5bb1aa1740935b7a

Hope I don't miss something this time =)

Comment (ymanton) [reply compel/test/infect/spy.c]: Thanks, applied in both tests.
