### PR TITLE
arm64: C/R PAC keys

### LINKED ISSUE #2595: Missing pointer-authentication code (PAC) C/R causing segfault on aarch64
## TLDR ##

CRIU does not checkpoint/restore pointer-authentication code (PAC)'s kernel state leading to segmentation faults post restoration.  The missing PAC keys leads to failed authentication of the program counter, leaving its upper 16 bits uncleared and resulting in the final segmentation fault.

According to the linux documentation ([pointer-authentication.txt](https://www.kernel.org/doc/Documentation/arm64/pointer-authentication.txt)), the kernel exposes a ptrace interface to support C/R of the PAC state:

```
Additionally, when CONFIG_CHECKPOINT_RESTORE is also set, the kernel
will expose the NT_ARM_PACA_KEYS and NT_ARM_PACG_KEYS regsets (struct
user_pac_address_keys and struct user_pac_generic_keys). These can be
used to get and set the keys for a thread.
```

## Description ##

We hit a segmentation fault when checkpointing/restoring a three-line python script in a container.  The python script does nothing but `time.sleep(...)` in a while loop, and the segmentation fault happens as soon as the restored python process returns from the sleep function.  It only repros on (CPU=aarch64, container image=ubuntu24.04).  The same setup works fine when (CPU=x86, container image=ubuntu24.04) or (CPU=aarch64, container image=ubuntu20.04).

## Environment ##

VM instance: [m7g.2xlarge](https://instances.vantage.sh/aws/ec2/m7g.2xlarge)
Host OS: `Linux ip-10-0-138-132 5.15.0-1072-aws #78~20.04.1-Ubuntu SMP Wed Oct 9 15:29:54 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`
Base container image: `public.ecr.aws/ubuntu/ubuntu:24.04_stable`
python version: `Python 3.12.3`
libc version: `ldd (Ubuntu GLIBC 2.39-0ubuntu8.4) 2.39`
test script:
```
import time

while True:
    time.sleep(1)
```

## Repros ##

1. Create a vanilla container based off public.ecr.aws/ubuntu/ubuntu:24.04_stable
2. Start the above python script within the container (use `nohup` if launched via an interactive shell)
3. Checkpoint the whole container
4. Create a new container from the checkpoint
5. The newly created container segfaults soon after `time.sleep(1)` returns

## Segfault ##

```
[Wed Feb 12 16:24:08 2025] potentially unexpected fatal signal 11.
[Wed Feb 12 16:24:08 2025] CPU: 3 PID: 14312 Comm: python3 Not tainted 5.15.0-1072-aws #78~20.04.1-Ubuntu
[Wed Feb 12 16:24:08 2025] Hardware name: Amazon EC2 m7g.2xlarge/, BIOS 1.0 11/1/2018
[Wed Feb 12 16:24:08 2025] pstate: 40001000 (nZcv daif -PAN -UAO -TCO -DIT +SSBS BTYPE=--)
[Wed Feb 12 16:24:08 2025] pc : 005200000056549c
[Wed Feb 12 16:24:08 2025] lr : 005200000056549c
[Wed Feb 12 16:24:08 2025] sp : 0000ffffd97cf780
[Wed Feb 12 16:24:08 2025] x29: 0000ffffd97cf780 x28: 0000000000b8a278 x27: 0000fffc6be25020
[Wed Feb 12 16:24:08 2025] x26: 0000000000000028 x25: 0000fffc6ba726b0 x24: 0000000000b1abc8
[Wed Feb 12 16:24:08 2025] x23: 00000000005ee3d0 x22: 0000fffc6b9d9516 x21: 0000fffc6be25080
[Wed Feb 12 16:24:08 2025] x20: 0000fffc6b9d9518 x19: 0000000000765fa0 x18: 0000000000000006
[Wed Feb 12 16:24:08 2025] x17: 0000fffc6bb8a6f4 x16: 0000000000a20bb0 x15: 0000000000000007
[Wed Feb 12 16:24:08 2025] x14: 00000000001056cc x13: 000000007fffffff x12: 000005c3ed912d54
[Wed Feb 12 16:24:08 2025] x11: 002f3a9d8c2315d6 x10: 0000000000000018 x9 : 00000000001bf1a0
[Wed Feb 12 16:24:08 2025] x8 : 0000000000000073 x7 : 00000000001bf1a0 x6 : 0000000000001792
[Wed Feb 12 16:24:08 2025] x5 : 0000000000b2cdb8 x4 : 0000000000000000 x3 : 0000000000000001
[Wed Feb 12 16:24:08 2025] x2 : 000000000000001b x1 : 0000fffc6be30e78 x0 : 0000000000a36798
[Wed Feb 12 16:24:08 2025] potentially unexpected fatal signal 11.
[Wed Feb 12 16:24:08 2025] CPU: 5 PID: 14285 Comm: sh Not tainted 5.15.0-1072-aws #78~20.04.1-Ubuntu
[Wed Feb 12 16:24:08 2025] Hardware name: Amazon EC2 m7g.2xlarge/, BIOS 1.0 11/1/2018
[Wed Feb 12 16:24:08 2025] pstate: 60001000 (nZCv daif -PAN -UAO -TCO -DIT +SSBS BTYPE=--)
[Wed Feb 12 16:24:08 2025] pc : 006caab32e335c0c
[Wed Feb 12 16:24:08 2025] lr : 006caab32e335c0c
[Wed Feb 12 16:24:08 2025] sp : 0000ffffceb3d890
[Wed Feb 12 16:24:08 2025] x29: 0000ffffceb3d890 x28: 0000000000000000 x27: 0000000000000000
[Wed Feb 12 16:24:08 2025] x26: 0000000000000000 x25: 0000aab35f4443a0 x24: 0000000000000000
[Wed Feb 12 16:24:08 2025] x23: 0000aab32e360200 x22: 0000aab32e360000 x21: 0000000000000001
[Wed Feb 12 16:24:08 2025] x20: 0000aab35f444480 x19: 0000000000000001 x18: 0000000000000003
[Wed Feb 12 16:24:08 2025] x17: 0000fffbb0857a10 x16: 0000aab32e35fd90 x15: 0000fffbb097aea0
[Wed Feb 12 16:24:08 2025] x14: 0000000000000001 x13: 000000000000002f x12: 0000ffffceb3da70
[Wed Feb 12 16:24:08 2025] x11: 00000000ffffffd8 x10: fffffffffffe89d0 x9 : 000000000000000d
[Wed Feb 12 16:24:08 2025] x8 : 0000aab35f444480 x7 : 0000000000000000 x6 : 000000000000008b
[Wed Feb 12 16:24:08 2025] x5 : 0000000000000000 x4 : 0000aab35f444490 x3 : 0000000000000000
[Wed Feb 12 16:24:08 2025] x2 : 0000000000000000 x1 : 0000000000000000 x0 : 0000000000001145
```

### PR DESCRIPTION
**Pull request by avagin**
PAC stands for Pointer Authentication Code. Each process has 5 PAC keys
    and a mask of enabled keys. All this properties have to be C/R-ed.
    
    As they are per-process protperties, we can save/restore them just for
    one thread.

Fixes #2595

### CODE REVIEW

File: criu/arch/aarch64/crtools.c [hunk 1]
```diff
@@ -20,10 +21,87 @@
...
+
+		pac_address_keys->pac_enabled_key = pac_enabled_key;
+
+	}
+	if (hwcaps & HWCAP_PACG) {
+		PacGenericKeys *pac_generic_keys;
+
+		iov.iov_base = &pacg;
+		iov.iov_len = sizeof(pacg);
+		if ((ret = ptrace(PTRACE_GETREGSET, pid, NT_ARM_PACG_KEYS, &iov))) {
```
Comment (aegiryy) [inline criu/arch/aarch64/crtools.c:89]: Do we need to worry about the kernels that are not compiled with PAC support (`CONFIG_ARM64_PTR_AUTH`)?  This allows the branch to be entered (as the hardware exhibits the capability), but the `ptrace` call will fail.

**Comment by aegiryy** [comment]
@avagin , thanks for drafting this PR!  Is this change going to be backward compatibility (e.g., able to restore checkpoints taken without the PAC state)?

File: criu/arch/aarch64/crtools.c (hunk 1 above)
Comment (avagin) [reply criu/arch/aarch64/crtools.c:89]: HWCAP_PACG isn't reported if the kernel isn't compiled with PAC.

**Comment by aegiryy** [comment]
> > @avagin , thanks for drafting this PR! Is this change going to be backward compatibility (e.g., able to restore checkpoints taken without the PAC state)?
> 
> @aegiryy yes, it is. Could you try it out on your workloads?
> 
> BTW: we need to check that CRIU handles SVE states correctly. I will file a separate issue for that.

Sure, we can test it on our end.

What are the SVE states you are referring to?  Does CRIU miss them as well?

File: criu/arch/aarch64/crtools.c [hunk 2]
```diff
@@ -20,10 +21,87 @@
...
+	hwcaps = 0;
+
+	pr_debug("%d: Dumping PAC keys\n", pid);
+	pac_entry = xmalloc(sizeof(PacKeys));
+	if (!pac_entry)
+		return -1;
+	core->ti_aarch64->pac_keys = pac_entry;
+	pac_keys__init(pac_entry);
+
+	if (hwcaps & HWCAP_PACA) {
```
Comment (rst0git) [inline criu/arch/aarch64/crtools.c:50]: Would it be possible to add a comment here that `HWCAP_PACG` indicates whether PAC is supported for pointers?

Perhaps we should move the `pr_debug("%d: Dumping PAC keys\n", pid);` inside this if statement?

File: criu/arch/aarch64/crtools.c [hunk 3]
```diff
@@ -20,10 +21,87 @@
...
+	long pac_enabled_key;
+	struct iovec iov;
+	int ret;
+
+	unsigned long hwcaps = getauxval(AT_HWCAP);
+
+	hwcaps = 0;
+
+	pr_debug("%d: Dumping PAC keys\n", pid);
+	pac_entry = xmalloc(sizeof(PacKeys));
```
Comment (rst0git) [inline criu/arch/aarch64/crtools.c:44]: Do we need to add `xfree(pac_entry)` somewhere?

File: criu/arch/aarch64/crtools.c [hunk 4]
```diff
@@ -135,3 +215,74 @@ int restore_gpregs(struct rt_sigframe *f, UserRegsEntry *r)
...
+	PacAddressKeys *paca;
+	PacGenericKeys *pacg;
+	long pac_enabled_keys;
+	struct user_pac_address_keys upaca;
+	struct user_pac_generic_keys upacg;
+	struct iovec iov;
+	int ret;
+
+
+	pr_debug("%d: Restoring PAC keys\n", pid);
```
Comment (rst0git) [inline criu/arch/aarch64/crtools.c:230]: What would happen if we create a checkpoint on a system with PAC keys and try to restore it on a system that does not support this? Would it make sense to check for `HWCAP_PACA` and show appropriate error message?

File: criu/arch/aarch64/crtools.c [hunk 5]
```diff
@@ -135,3 +215,74 @@ int restore_gpregs(struct rt_sigframe *f, UserRegsEntry *r)
...
+		upaca.apiakey = paca->apiakey_lo + ((__uint128_t)paca->apiakey_hi << 64);
+		upaca.apibkey = paca->apibkey_lo + ((__uint128_t)paca->apibkey_hi << 64);
+		upaca.apdakey = paca->apdakey_lo + ((__uint128_t)paca->apdakey_hi << 64);
+		upaca.apdbkey = paca->apdbkey_lo + ((__uint128_t)paca->apdbkey_hi << 64);
+
+		iov.iov_base = &upaca;
+		iov.iov_len = sizeof(upaca);
+
+		if ((ret = ptrace(PTRACE_SETREGSET, pid, NT_ARM_PACA_KEYS, &iov))) {
+			pr_perror("Failed to obtain FPU registers for %d", pid);
```
Comment (rst0git) [inline criu/arch/aarch64/crtools.c:246]: It looks like we need to update the text in these error messages?

File: criu/arch/aarch64/crtools.c [hunk 6]
```diff
@@ -20,10 +21,87 @@
...
+		pac_address_keys->apdakey_lo = paca.apdakey;
+		pac_address_keys->apdakey_hi = paca.apdakey >> 64;
+		pac_address_keys->apdbkey_lo = paca.apdbkey;
+		pac_address_keys->apdbkey_hi = paca.apdbkey >> 64;
+
+		iov.iov_base = &pac_enabled_key;
+		iov.iov_len = sizeof(pac_enabled_key);
+		ret = ptrace(PTRACE_GETREGSET, pid, NT_ARM_PAC_ENABLED_KEYS, &iov);
+		if (ret) {
+			pr_perror("Failed to obtain FPU registers for %d", pid);
```
Comment (rst0git) [inline criu/arch/aarch64/crtools.c:77]: same here?

File: criu/arch/aarch64/crtools.c [hunk 7]
```diff
@@ -135,3 +220,83 @@ int restore_gpregs(struct rt_sigframe *f, UserRegsEntry *r)
...
+	int ret;
+
+
+	pr_debug("%d: Restoring PAC keys\n", pid);
+
+	paca = &rsti(item)->arch_info.pac_address_keys;
+	pacg = &rsti(item)->arch_info.pac_generic_keys;
+	if (rsti(item)->arch_info.has_paca) {
+		if (!(hwcaps & HWCAP_PACA)) {
+			pr_err("PACG support is required from the source system");
```
Comment (rst0git) [inline criu/arch/aarch64/crtools.c:242]: We need to add `\n` in these error messages.
```
$ make lint 
...
! git --no-pager grep -En '^\s*\<pr_(err|warn|msg|info|debug)\>.*);$' | grep -v '\\n'
criu/arch/aarch64/crtools.c:242:			pr_err("PACG support is required from the source system");
criu/arch/aarch64/crtools.c:269:			pr_err("PACG support is required from the source system.");
```

**Comment by adrianreber** [comment]
No, nothing is backported usually. There will be just a new release from the criu-dev branch at some point.

**Comment by aegiryy** [comment]
> No, nothing is backported usually. There will be just a new release from the criu-dev branch at some point.

@adrianreber Thanks for the immediate reply!  This is a "new feature" instead of a bugfix so it probably doesn't qualify for backporting anyway.  We will cherry-pick the change and manually resolve the conflicts then.

File: test/zdtm/static/Makefile [hunk 8]
```diff
@@ -66,6 +66,7 @@ TST_NOFILE	:=				\
 		pipe01				\
 		pipe02				\
 		pthread00			\
+		pthread00-pac			\
```
Comment (rst0git) [inline test/zdtm/static/Makefile:69]: @avagin This test seems to pass with and without the patch for c/r of PAC keys. Do you have any ideas how to verity that the PAC keys are restored?

Comment (avagin) [reply test/zdtm/static/Makefile:69]: The test fails if I revert "arm64: C/R PAC keys":
```
root@ubuntu-2410-arm64:/home/avagin/criu# python3 test/zdtm.py run -t zdtm/static/pthread00-pac
userns is supported
=== Run 1/1 ================ zdtm/static/pthread00-pac
====================== Run zdtm/static/pthread00-pac in h ======================
Start test
./pthread00-pac --pidfile=pthread00-pac.pid --outfile=pthread00-pac.out
Run criu dump
Run criu restore
Send the 15 signal to  38
tail: cannot open 'zdtm/static/pthread00-pac.out' for reading: No such file or directory
=================== zdtm/static/pthread00-pac.out.inprogress ===================
18:37:13.957:    38: ./pthread00-pac pid 38
18:37:13.957:    38: Waiting until all threads are ready
18:37:13.995:    38: Waiting while all threads are joined
18:37:13.995:    38: Waiting for 43

=================== zdtm/static/pthread00-pac.out.inprogress ===================
############# Test zdtm/static/pthread00-pac FAIL at result check ##############
Test output: ================================
18:37:13.957:    38: ./pthread00-pac pid 38
18:37:13.957:    38: Waiting until all threads are ready
18:37:13.995:    38: Waiting while all threads are joined
18:37:13.995:    38: Waiting for 43

 <<< ================================
##################################### FAIL #####################################
```

Comment (rst0git) [reply test/zdtm/static/Makefile:69]: Thank you for confirming! The aarch64 VM I was using for testing must have been missing something.

**Review by rst0git — APPROVED** [review]
LGTM

File: test/zdtm/static/Makefile (hunk 8 above)
Comment (avagin) [reply test/zdtm/static/Makefile:69]: Does it support PAC keys?
``` 
cat /proc/cpuinfo | grep paca
```

Comment (rst0git) [reply test/zdtm/static/Makefile:69]: You are right, this was the problem:
```
# cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 50.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 1
BogoMIPS	: 50.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 2
BogoMIPS	: 50.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

# lscpu
Architecture:             aarch64
  CPU op-mode(s):         32-bit, 64-bit
  Byte Order:             Little Endian
CPU(s):                   3
  On-line CPU(s) list:    0-2
Vendor ID:                ARM
  BIOS Vendor ID:         QEMU
  Model name:             Neoverse-N1
    BIOS Model name:      virt-rhel8.6.0  CPU @ 2.0GHz
    BIOS CPU family:      1
    Model:                1
    Thread(s) per core:   1
    Core(s) per socket:   1
    Socket(s):            3
    Stepping:             r3p1
    BogoMIPS:             50.00
    Flags:                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
NUMA:                     
  NUMA node(s):           1
  NUMA node0 CPU(s):      0-2
Vulnerabilities:          
  Gather data sampling:   Not affected
  Itlb multihit:          Not affected
  L1tf:                   Not affected
  Mds:                    Not affected
  Meltdown:               Not affected
  Mmio stale data:        Not affected
  Reg file data sampling: Not affected
  Retbleed:               Not affected
  Spec rstack overflow:   Not affected
  Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:             Mitigation; __user pointer sanitization
  Spectre v2:             Mitigation; CSV2, BHB
  Srbds:                  Not affected
  Tsx async abort:        Not affected
```
