### PR TITLE
criu/log: properly handle truncated length from vsnprintf

### LINKED ISSUE #2781: runc tests fail with criu-dev
For the last few years, runc repo have a CI job to test runc against criu-dev branch, mostly to catch some regressions early.

We are seeing failures recently (this week), alas without too much diagnostics.

For example (from [here](https://productionresultssa6.blob.core.windows.net/actions-results/865121f5-ae53-4a5d-a72a-1f3aace783d2/workflow-job-run-15406e29-e965-5079-8b70-bbc24930c4cb/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-10-16T17%3A41%3A00Z&sig=F9TpGdybzQNGVNqU1oT0IKHCEtLAy%2BqSiUzOFRMHqt8%3D&ske=2025-10-17T05%3A10%3A53Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-10-16T17%3A10%3A53Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2025-10-16T17%3A30%3A55Z&sv=2025-11-05), look for `not ok 32`):
```
2025-10-16T01:03:57.5662977Z not ok 32 checkpoint and restore
2025-10-16T01:03:57.5673614Z # (from function `simple_cr' in file tests/integration/checkpoint.bats, line 131,
2025-10-16T01:03:57.5675071Z #  in test file tests/integration/checkpoint.bats, line 192)
2025-10-16T01:03:57.5698743Z #   `simple_cr' failed
2025-10-16T01:03:57.5712389Z # runc spec (status=0)
2025-10-16T01:03:57.5713588Z #
2025-10-16T01:03:57.5714281Z # runc run -d --console-socket /tmp/bats-run-kiFEqC/runc.CtdpiC/tty/sock test_busybox (status=0)
2025-10-16T01:03:57.5715346Z #
2025-10-16T01:03:57.5715677Z # runc state test_busybox (status=0)
2025-10-16T01:03:57.5716304Z # {
2025-10-16T01:03:57.5716613Z #   "ociVersion": "1.2.1+dev",
2025-10-16T01:03:57.5716999Z #   "id": "test_busybox",
2025-10-16T01:03:57.5717360Z #   "pid": 13992,
2025-10-16T01:03:57.5717695Z #   "status": "running",
2025-10-16T01:03:57.5718167Z #   "bundle": "/tmp/bats-run-kiFEqC/runc.CtdpiC/bundle",
2025-10-16T01:03:57.5718804Z #   "rootfs": "/tmp/bats-run-kiFEqC/runc.CtdpiC/bundle/rootfs",
2025-10-16T01:03:57.5719398Z #   "created": "2025-10-16T01:03:57.172483254Z",
2025-10-16T01:03:57.5719845Z #   "owner": ""
2025-10-16T01:03:57.5720295Z # }
2025-10-16T01:03:57.5720817Z # runc checkpoint --work-path ./work-dir test_busybox (status=1)
2025-10-16T01:03:57.5721697Z # time="2025-10-16T01:03:57Z" level=warning msg="open work-dir/dump.log: no such file or directory"
2025-10-16T01:03:57.5722327Z # time="2025-10-16T01:03:57Z" level=error msg="read unixpacket @->@: EOF"
2025-10-16T01:03:57.5722676Z # --- teardown ---
```

It seems that criu swrk just dies under (without even leaving `dump.log`).

Tried to reproduce it locally with no luck so far.

### PR DESCRIPTION
**Pull request by avagin**
vsnprintf does not always return the number of bytes actually written to the buffer.

If the output was truncated due to the buffer limit, the return value is the total number of bytes which WOULD have been written to the final string if enough space had been available.

This means we must cap the return value to the buffer size excluding the terminating null byte to correctly calculate the log entry size.

Fixes #2781

### CODE REVIEW

**Review by rst0git — APPROVED** [review]
LGTM


I was able to confirm that this change fixes the error in https://github.com/checkpoint-restore/criu/issues/2781

File: criu/log.c [hunk 1]
```diff
@@ -320,7 +320,7 @@ unsigned int log_get_loglevel(void)
 
 static void early_vprint(const char *format, unsigned int loglevel, va_list params)
 {
-	unsigned int log_size = 0;
+	int log_size = 0, log_space;
 	struct early_log_hdr *hdr;
 
 	if ((early_log_buf_off + sizeof(hdr)) >= EARLY_LOG_BUF_LEN)
```
Comment (kolyshkin) [inline criu/log.c]: It looks like usage of `sizeof(hdr)` is also wrong here (and in other two places), because `hdr` is a pointer (8 bytes on x86_64). It should be replaced with `sizeof(struct early_log_hdr)` (4 bytes) like in your new code above.

**Review by kolyshkin — COMMENTED** [review]
One more (minor) issue found.

File: criu/log.c (hunk 1 above)
Comment (kolyshkin) [reply criu/log.c]: ...or `sizeof(*hdr)`

Comment (avagin) [reply criu/log.c]: They are consistent in all places and they use the size that is greater than the right one, so everything works as it should be :)

**Review by kolyshkin — APPROVED** [review]
