### PR TITLE
criu/test: fix scanf format and type mismatches

### LINKED ISSUE #332: Fixup scanf formats vs variables' types
https://www.codacy.com/app/xemul/criu/issues?bid=4795042&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiQ29kZSBTdHlsZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOlsyMjM5XX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfSx7InZhbHVlcyI6W119XQ==

### PR DESCRIPTION
**Pull request by cheese-cakee**
### What this PR does
Aligns scanf/sprintf format specifiers with destination variable types in targeted places from #332, and separates an error-path fd-close fix into its own logical commit.

### Why
Type/format mismatches can cause undefined behavior or compiler/static-analysis warnings across platforms/toolchains.

### Changes
- criu/proc_parse.c
  - Parse eventpoll 	fd with PRIu32.
  - Keep uid/gid option parsing/formatting aligned to unsigned values.
- 	est/others/bers/bers.c
  - Use %zu for size_t values.
- 	est/zdtm/lib/bpfmap_zdtm.c
  - Parse rozen with PRIu32.
- 	est/zdtm/static/packet_sock_mmap.c
  - Parse end address explicitly (instead of assignment suppression with length modifier) to satisfy gnu_scanf checks.
- 	est/zdtm/static/ipc_namespace.c
  - Write only formatted bytes via strlen(buf).
  - In a separate commit, close d on write error paths.

### Commit structure
1. 	est/criu: align scanf/sprintf formats with destination types
2. zdtm/ipc: close fd on write error paths

### Validation
- Existing CI matrix on the PR is used for validation.
- Local full build/test was not run in this Windows shell environment.

Fixes: #332

### CODE REVIEW

File: criu/proc_parse.c [hunk 1]
```diff
@@ -1933,7 +1933,7 @@ static int parse_fdinfo_pid_s(int pid, int fd, int type, void *arg)
 			goto out;
 
 		if (fdinfo_field(str, "pos") || fdinfo_field(str, "flags") || fdinfo_field(str, "mnt_id")) {
-			unsigned long long val;
+			long long val;
```
Comment (avagin) [inline criu/proc_parse.c]: why?

Comment (cheese-cakee) [reply criu/proc_parse.c]: thanks for pointing out, I reverted this back to unsigned (unsigned long long) and switched the parse to %llu to keep original semantics for fdinfo numeric fields.

File: criu/proc_parse.c [hunk 2]
```diff
@@ -1262,12 +1262,12 @@ static bool sb_opt_cb(char *opt, char *unknown, size_t *uoff)
...
-	if (sscanf(opt, "gid=%d", &id) == 1) {
+	if (sscanf(opt, "gid=%u", &id) == 1) {
 		*uoff += sprintf(unknown + *uoff, "gid=%d", userns_gid(id));
 		unknown[*uoff] = ',';
 		(*uoff)++;
 		return true;
-	} else if (sscanf(opt, "uid=%d", &id) == 1) {
+	} else if (sscanf(opt, "uid=%u", &id) == 1) {
 		*uoff += sprintf(unknown + *uoff, "uid=%d", userns_uid(id));
 		unknown[*uoff] = ',';
```
[the remark this answers is not in the document]
Comment (cheese-cakee) [reply criu/proc_parse.c:1277]: Addressed. I changed the corresponding sprintf formats to %u for userns_gid() / userns_uid() output.

File: criu/proc_parse.c [hunk 3]
```diff
@@ -2038,7 +2038,7 @@ static int parse_fdinfo_pid_s(int pid, int fd, int type, void *arg)
 			eventpoll_tfd_entry__init(e);
 
 			ret = sscanf(str,
-				     "tfd: %d events: %x data: %llx"
+				     "tfd: %u events: %x data: %llx"
 				     " pos:%lli ino:%lx sdev:%x",
 				     &e->tfd, &e->events, (long long *)&e->data, (long long *)&e->pos,
 				     (long *)&e->inode, &e->dev);
```
[the remark this answers is not in the document]
Comment (cheese-cakee) [reply criu/proc_parse.c:2055]: Addressed. I removed the pointer casts and now parse into correctly typed temporaries (unsigned int / unsigned long long) before assigning into protobuf fields.

File: test/zdtm/static/packet_sock_mmap.c [hunk 4]
```diff
@@ -43,7 +43,7 @@ static void check_map_is_there(unsigned long addr, int sk)
 	while (fgets(line, sizeof(line), f) != NULL) {
 		unsigned long long ino;
 		unsigned long start;
-		int maj, min;
+		unsigned int maj, min;
 
 		sscanf(line, "%lx-%*x %*s %*s %x:%x %llu %*s", &start, &maj, &min, &ino);
 		if ((start == addr) && ss.st_dev == makedev(maj, min) && ss.st_ino == ino) {
```
[the remark this answers is not in the document]
Comment (cheese-cakee) [reply test/zdtm/static/packet_sock_mmap.c:49]: Applied. Updated the skipped end-address format from %*x to %*lx in packet_sock_mmap.c.

File: criu/proc_parse.c [hunk 5]
```diff
@@ -1262,12 +1262,12 @@ static bool sb_opt_cb(char *opt, char *unknown, size_t *uoff)
 {
 	unsigned int id;
 
-	if (sscanf(opt, "gid=%d", &id) == 1) {
+	if (sscanf(opt, "gid=%u", &id) == 1) {
 		*uoff += sprintf(unknown + *uoff, "gid=%d", userns_gid(id));
 		unknown[*uoff] = ',';
```
[the remark this answers is not in the document]
Comment (cheese-cakee) [reply criu/proc_parse.c:1272]: Addressed together with the uid case: output format now uses %u for mapped gid/uid.

**Comment by cheese-cakee** [comment]
@avagin please give it a review when possible.thankyou.

**Comment by cheese-cakee** [comment]
@avagin all inline comments on this PR are addressed. 
 
   I checked the remaining ci/circleci: test-local-gcc failure
   more closely, and the visible CircleCI tail only shows VM/kernel/AppArmor boot logs ending in make -C scripts/ci
   local exiting with code 2. I couldn’t find a concrete compiler error or a failure tied to the touched changes.
   
   If this looks like the usual local CI issue, could you please take another look at the PR when you have a
   moment? Thanks.

**Comment by avagin** [comment]
```
gcc -g -O2 -Wall -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -Wdeclaration-after-statement -Wstrict-prototypes   -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -I../lib -iquote ../lib/arch/x86/include -c packet_sock_spkt.c -o packet_sock_spkt.o
packet_sock_mmap.c: In function ‘check_map_is_there’:
packet_sock_mmap.c:48:30: error: use of assignment suppression and length modifier together in gnu_scanf format [-Werror=format=]
   48 |                 sscanf(line, "%lx-%*lx %*s %*s %x:%x %llu %*s", &start, &maj, &min, &ino);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

File: criu/proc_parse.c [hunk 6]
```diff
@@ -2038,7 +2038,7 @@ static int parse_fdinfo_pid_s(int pid, int fd, int type, void *arg)
 			eventpoll_tfd_entry__init(e);
 
 			ret = sscanf(str,
-				     "tfd: %d events: %x data: %llx"
+				     "tfd: %u events: %x data: %llx"
```
Comment (Snorch) [inline criu/proc_parse.c]:
```
struct  EventpollTfdEntry
{                       
...
  uint32_t tfd;  
```
So I guess %u is also incorrect here. Probably `%" PRIu32 "` right?

File: test/zdtm/lib/bpfmap_zdtm.c [hunk 7]
```diff
@@ -57,7 +57,7 @@ int parse_bpfmap_fdinfo(int fd, struct bpfmap_fdinfo_obj *obj, uint32_t expected
 			continue;
 		}
 		if (fdinfo_field(str, "frozen")) {
-			if (sscanf(str, "frozen: %d", &obj->frozen) != 1)
+			if (sscanf(str, "frozen: %u", &obj->frozen) != 1)
```
Comment (Snorch) [inline test/zdtm/lib/bpfmap_zdtm.c]: Maybe `%" PRIu32 "`?

File: test/zdtm/static/ipc_namespace.c [hunk 8]
```diff
@@ -221,10 +221,11 @@ static int rand_ipc_sysctl(char *name, unsigned int val)
 		pr_perror("Can't open %s", name);
 		return fd;
 	}
-	sprintf(buf, "%d\n", val);
+	sprintf(buf, "%u\n", val);
 	ret = write(fd, buf, strlen(buf));
 	if (ret < 0) {
 		pr_perror("Can't write %u into %s", val, name);
+		close(fd);
```
Comment (Snorch) [inline test/zdtm/static/ipc_namespace.c:233]: It feels like missing close on error path deserves a separate logical commit. Can you please split it?

**Comment by cheese-cakee** [comment]
I force-pushed a cleanup pass to keep the changes strictly surgical and commit scopes explicit:

- 9561d0714 format/type alignment changes only
- c91004ff5 separate close(fd) error-path fix in ipc_namespace.c

Also refreshed PR description to match the current diff and commit split.

@Snorch @avagin please re-check when convenient.

File: test/zdtm/static/packet_sock_mmap.c [hunk 9]
```diff
@@ -42,10 +42,11 @@ static void check_map_is_there(unsigned long addr, int sk)
 	f = fopen("/proc/self/maps", "r");
 	while (fgets(line, sizeof(line), f) != NULL) {
 		unsigned long long ino;
-		unsigned long start;
-		int maj, min;
+		unsigned long start, end;
+		unsigned int maj, min;
 
-		sscanf(line, "%lx-%*x %*s %*s %x:%x %llu %*s", &start, &maj, &min, &ino);
+		sscanf(line, "%lx-%lx %*s %*s %x:%x %llu %*s", &start, &end, &maj, &min, &ino);
```
Comment (Snorch) [inline test/zdtm/static/packet_sock_mmap.c]: Instead of adding unused variable `end` maybe we can do `%*lx` to just skip the second match with the right type?

Comment (cheese-cakee) [reply test/zdtm/static/packet_sock_mmap.c]: implemented

Comment (Snorch) [reply test/zdtm/static/packet_sock_mmap.c]: Test `ci/circleci: test-local-gcc` fails with:
```
packet_sock_mmap.c:48:30: error: use of assignment suppression and length modifier together in gnu_scanf format [-Werror=format=]
   48 |                 sscanf(line, "%lx-%*lx %*s %*s %x:%x %llu %*s", &start, &maj, &min, &ino);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
So there is no need to patch this line, original `%*x` was perfectly correct.

**Comment by cheese-cakee** [comment]
Thanks for catching this. I reverted this specific parse fragment back to `%*x` in `packet_sock_mmap.c` to avoid the `gnu_scanf` `-Werror` issue with assignment suppression + length modifier.

**Comment by cheese-cakee** [comment]
@avagin @Snorch Requesting final review when convenient

**Comment by Snorch** [comment]
These two last commits:
[zdtm: avoid gnu_scanf warning on maps parse](https://github.com/checkpoint-restore/criu/pull/2915/changes/9713c28d5c309a202f496a75cfbc301ec5798073)
[zdtm: use suppressed %*lx for maps end field](https://github.com/checkpoint-restore/criu/pull/2915/changes/ea3936f7d31b3aee4c7bfd491fb5eb68c1e2d55b)

should be merged (squashed) into
[test/criu: align scanf/sprintf formats with destination types](https://github.com/checkpoint-restore/criu/pull/2915/changes/9561d0714bcd349196012686baed27d392ee94df)

Please do.

See https://github.com/checkpoint-restore/criu/blob/criu-dev/CONTRIBUTING.md#pull-request-guidelines:
```
Please merge the fixup commits into the commits that has introduced the problem
```

**Comment by cheese-cakee** [comment]
> These two last commits: [zdtm: avoid gnu_scanf warning on maps parse](https://github.com/checkpoint-restore/criu/pull/2915/changes/9713c28d5c309a202f496a75cfbc301ec5798073) [zdtm: use suppressed %*lx for maps end field](https://github.com/checkpoint-restore/criu/pull/2915/changes/ea3936f7d31b3aee4c7bfd491fb5eb68c1e2d55b)
> 
> should be merged (squashed) into [test/criu: align scanf/sprintf formats with destination types](https://github.com/checkpoint-restore/criu/pull/2915/changes/9561d0714bcd349196012686baed27d392ee94df)
> 
> Please do.
> 
> See https://github.com/checkpoint-restore/criu/blob/criu-dev/CONTRIBUTING.md#pull-request-guidelines:
> 
> ```
> Please merge the fixup commits into the commits that has introduced the problem
> ```

done

**Review by Snorch — APPROVED** [review]
Looks good. Thanks.

**Comment by Snorch** [comment]
One more thing, can it be that fails of [CI / nftables-test (pull_request)](https://github.com/checkpoint-restore/criu/actions/runs/23559894149/job/68601449737?pr=2915) are somehow related to this PR?

```
==================== Run zdtm/static/mnt_ext_master in uns =====================
Start test
./mnt_ext_master --pidfile=mnt_ext_master.pid --outfile=mnt_ext_master.out --dirname=mnt_ext_master.test
munmap_chunk(): invalid pointer
Run criu dump
=[log]=> dump/zdtm/static/mnt_ext_master/202/1/dump.log
------------------------ grep Error ------------------------
b'(00.000642) cpu: x86_family 25 x86_vendor_id AuthenticAMD x86_model_id AMD EPYC 7763 64-Core Processor'
b'(00.000657) cpu: fpu: xfeatures_mask 0x5 xsave_size 832 xsave_size_max 832 xsaves_size 848'
b'(00.000666) cpu: fpu: x87 floating point registers     xstate_offsets      0 / 0      xstate_sizes    160 / 160'
b'(00.000668) cpu: fpu: AVX registers                    xstate_offsets    576 / 576    xstate_sizes    256 / 256'
b"(00.000677) Warn  (criu/kerndat.c:1769): ioctl(PAGEMAP_SCAN) doesn't support PAGE_IS_GUARD flag. CRIU dump will fail if dumped processes use madvise(MADV_GUARD_INSTALL). Please, consider updating your kernel."
------------------------ ERROR OVER ------------------------
############## Test zdtm/static/mnt_ext_master FAIL at CRIU dump ###############
```

Some vague fail without any proper error, on mount related test and this PR touches sb_opt_cb in mountinfo parsing code.

(same for mnt_ext_auto, mnt_ext_file_bind_auto and mnt_tracefs tests)

**Comment by adrianreber** [comment]
Having worked on CI runs recently I haven't seen that error you just mentioned. The nftables is indeed running on the default kernel form GitHub Actions and not on some VM with a newer kernel (not sure if that is rleated):
```
Linux runnervm46oaq 6.14.0-1017-azure #17~24.04.1-Ubuntu SMP Mon Dec  1 20:10:50 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

File: criu/proc_parse.c [hunk 10]
```diff
@@ -2038,7 +2038,7 @@ static int parse_fdinfo_pid_s(int pid, int fd, int type, void *arg)
 			eventpoll_tfd_entry__init(e);
 
 			ret = sscanf(str,
-				     "tfd: %d events: %x data: %llx"
+				     "tfd: %" PRIu32 " events: %x data: %llx"
```
Comment (Snorch) [inline criu/proc_parse.c]: Maybe for scan we should use SCNu32.

**Comment by Snorch** [comment]
I pushed [proc_parse: Preallocate extra space for possible option string growth](https://github.com/checkpoint-restore/criu/pull/2915/changes/5b4ec82d3ffa9e11c96a1de6afcefc1d80bba412) fix which might help with this criu dump abrt.

File: test/zdtm/static/ipc_namespace.c [hunk 11]
```diff
@@ -245,9 +245,9 @@ static int rand_ipc_sem(void)
 		pr_perror("Can't open %s", name);
 		return fd;
 	}
-	sprintf(buf, "%d %d %d %d\n", (unsigned)lrand48(), (unsigned)lrand48(), (unsigned)lrand48(),
+	sprintf(buf, "%u %u %u %u\n", (unsigned)lrand48(), (unsigned)lrand48(), (unsigned)lrand48(),
```
Comment (avagin) [inline test/zdtm/static/ipc_namespace.c]: please use snprintf to be sure that it does write beyond buffer boundaries.

File: test/zdtm/static/ipc_namespace.c [hunk 12]
```diff
@@ -245,9 +245,9 @@ static int rand_ipc_sem(void)
...
 		(unsigned)lrand48() % MAX_MNI);
-	ret = write(fd, buf, 128);
+	ret = write(fd, buf, strlen(buf));
```
Comment (avagin) [inline test/zdtm/static/ipc_namespace.c]: snprintf returns a number of bytes written to the buffer

File: test/zdtm/static/ipc_namespace.c (hunk 11 above)
Comment (cheese-cakee) [reply test/zdtm/static/ipc_namespace.c]: addressed both

File: test/zdtm/static/ipc_namespace.c [hunk 13]
```diff
@@ -246,9 +250,13 @@ static int rand_ipc_sem(void)
 		pr_perror("Can't open %s", name);
 		return fd;
 	}
-	sprintf(buf, "%u %u %u %u\n", (unsigned)lrand48(), (unsigned)lrand48(), (unsigned)lrand48(),
-		(unsigned)lrand48() % MAX_MNI);
-	ret = write(fd, buf, strlen(buf));
+	ret = snprintf(buf, sizeof(buf), "%u %u %u %u\n", (unsigned)lrand48(), (unsigned)lrand48(),
+		       (unsigned)lrand48(), (unsigned)lrand48() % MAX_MNI);
+	if (ret < 0 || ret >= sizeof(buf)) {
+		close(fd);
```
Comment (avagin) [inline test/zdtm/static/ipc_namespace.c:258]: you need to print a error message here

**Comment by avagin** [comment]
```
test/criu: align scanf/sprintf formats with destination types
- use PRIu32 for eventpoll tfd and bpfmap frozen parsing
- align uid/gid and size_t format specifiers
- fix ipc_namespace sysctl helpers to write only formatted bytes
- keep packet_sock_mmap parser at %*x to avoid gnu_scanf -Werror warning, while using unsigned maj/min types
```

I think it is better to split this change into a few patches for each logic change.

**Comment by cheese-cakee** [comment]
Thanks for the review feedbacks @avagin  @Snorch . I reworked the branch to follow the latest comments more closely.

In particular:
- I split the previous mixed change into smaller patches by logical area, instead of keeping the format/parser/test changes bundled together
- I kept the ipc write-error handling split out as its own change
- I kept Pavel's proc_parse allocation fix separate
- I switched the remaining scanf() sites to the matching SCN* macros
- I added explicit error reporting on the snprintf() failure/truncation paths in ipc_namespace.c

Current stack:
- proc_parse: fix format parsing types
- tests: align format specifiers with destination types
- zdtm/packet_sock_mmap: keep warning-free parsing
- zdtm/ipc: close fd on write error paths
- zdtm/ipc: use snprintf and bounded writes for sysctl buffers
- proc_parse: Preallocate extra space for possible option string growth
- zdtm/bpfmap: use SCNu32 for frozen parsing

The goal here was to make each patch easier to review and to reflect the requested commit structure without adding unrelated changes.

File: test/zdtm/static/ipc_namespace.c [hunk 14]
```diff
@@ -225,6 +225,7 @@ static int rand_ipc_sysctl(char *name, unsigned int val)
 	ret = write(fd, buf, strlen(buf));
 	if (ret < 0) {
 		pr_perror("Can't write %u into %s", val, name);
+		close(fd);
 		return -errno;
```
Comment (avagin) [inline test/zdtm/static/ipc_namespace.c]: close can corrupt errno.

**Comment by avagin** [comment]
LGTM

File: test/zdtm/static/ipc_namespace.c (hunk 14 above)
Comment (Snorch) [reply test/zdtm/static/ipc_namespace.c]: Good catch. I think we should replace `return -errno` with `return -1`. (as `pr_perror` already prints errno, plus the returned errno is never used later (only to indicate general failure))

And also `return fd` above is also strange, where is no reason not to replace with `return -1`.

**Comment by Snorch** [comment]
Final code looks ok (except see the Andrei's and mine comments about errno), but the splitting to commits is odd:

1) Fixup hunks should be merged into the commits introducing the problem (I already previously pointed you to relevant part of contribution guide)

```
criu$ git log -p test/zdtm/lib/bpfmap_zdtm.c
commit fb593ffcba798506787e7e39429520c5608191df (HEAD -> cheese-cake/scanf-format-v3)
Author: Farzan Aman Khan <farzanaman99@gmail.com>
Date:   Fri Mar 27 20:59:06 2026 +0530

    zdtm/bpfmap: use SCNu32 for frozen parsing
    
    Signed-off-by: Farzan Aman Khan <farzanaman99@gmail.com>

diff --git a/test/zdtm/lib/bpfmap_zdtm.c b/test/zdtm/lib/bpfmap_zdtm.c
index 81cf3f1c7..9c1abba84 100644
--- a/test/zdtm/lib/bpfmap_zdtm.c
+++ b/test/zdtm/lib/bpfmap_zdtm.c
@@ -57,7 +57,7 @@ int parse_bpfmap_fdinfo(int fd, struct bpfmap_fdinfo_obj *obj, uint32_t expected
                        continue;
                }
                if (fdinfo_field(str, "frozen")) {
-                       if (sscanf(str, "frozen: %" PRIu32 "", &obj->frozen) != 1)
+                       if (sscanf(str, "frozen: %" SCNu32 "", &obj->frozen) != 1)
                                goto parse_err;
                        met++;
                        continue;

commit 8f23e01ca2d416c769ae7cba374a52bbe3493619
Author: Farzan Aman Khan <farzanaman99@gmail.com>
Date:   Fri Mar 27 20:50:37 2026 +0530

    tests: align format specifiers with destination types
    
    Signed-off-by: Farzan Aman Khan <farzanaman99@gmail.com>

diff --git a/test/zdtm/lib/bpfmap_zdtm.c b/test/zdtm/lib/bpfmap_zdtm.c
index 7fe1ed182..81cf3f1c7 100644
--- a/test/zdtm/lib/bpfmap_zdtm.c
+++ b/test/zdtm/lib/bpfmap_zdtm.c
@@ -57,7 +57,7 @@ int parse_bpfmap_fdinfo(int fd, struct bpfmap_fdinfo_obj *obj, uint32_t expected
                        continue;
                }
                if (fdinfo_field(str, "frozen")) {
-                       if (sscanf(str, "frozen: %d", &obj->frozen) != 1)
+                       if (sscanf(str, "frozen: %" PRIu32 "", &obj->frozen) != 1)
                                goto parse_err;
                        met++;
                        continue;


```
Same line of code touched in multiple commits in one PR is a bad sign.

2. Commit messages are too dry:

```
commit ca97bd03630c1d669ece02383789e1bdfe376154
Author: Farzan Aman Khan <farzanaman99@gmail.com>
Date:   Fri Mar 27 20:50:21 2026 +0530

    proc_parse: fix format parsing types
    
    Signed-off-by: Farzan Aman Khan <farzanaman99@gmail.com>

diff --git a/criu/proc_parse.c b/criu/proc_parse.c
index f51f2e801..affa956bf 100644
--- a/criu/proc_parse.c
+++ b/criu/proc_parse.c
@@ -1262,13 +1262,13 @@ static bool sb_opt_cb(char *opt, char *unknown, size_t *uoff)
 {
        unsigned int id;
 
-       if (sscanf(opt, "gid=%d", &id) == 1) {
-               *uoff += sprintf(unknown + *uoff, "gid=%d", userns_gid(id));
+       if (sscanf(opt, "gid=%u", &id) == 1) {
+               *uoff += sprintf(unknown + *uoff, "gid=%u", userns_gid(id));
                unknown[*uoff] = ',';
```
You should explain exactly what are you fixing and why in the commit message. E.g.: X has type T, so we need to use format specifier F when printing/scanning it.

**Comment by cheese-cakee** [comment]
Addressed the errno/return-path review points in ipc_namespace.c:

- replaced 
eturn -errno after close(fd) with 
eturn -1 in rand_ipc_sysctl()/rand_ipc_sem();
- replaced 
eturn fd on open failure with 
eturn -1 in those helpers.

Kept the stack restacked/clean (no extra fixup commit on top).

**Comment by cheese-cakee** [comment]
i have fixed the commits according to what you wanted @Snorch

File: test/zdtm/static/ipc_namespace.c [hunk 15]
```diff
@@ -219,13 +219,19 @@ static int rand_ipc_sysctl(char *name, unsigned int val)
...
-		return fd;
+		return -1;
 	}
-	sprintf(buf, "%d\n", val);
-	ret = write(fd, buf, strlen(buf));
+	ret = snprintf(buf, sizeof(buf), "%u\n", val);
+	if (ret < 0 || ret >= sizeof(buf)) {
+		pr_err("Can't format %u for %s\n", val, name);
+		close(fd);
+		return -EINVAL;
```
Comment (Snorch) [inline test/zdtm/static/ipc_namespace.c]: let's replace -EINVAL with -1, since only success/failure matters

File: test/zdtm/static/ipc_namespace.c [hunk 16]
```diff
@@ -243,14 +249,20 @@ static int rand_ipc_sem(void)
...
 	}
-	sprintf(buf, "%d %d %d %d\n", (unsigned)lrand48(), (unsigned)lrand48(), (unsigned)lrand48(),
-		(unsigned)lrand48() % MAX_MNI);
-	ret = write(fd, buf, 128);
+	ret = snprintf(buf, sizeof(buf), "%u %u %u %u\n", (unsigned)lrand48(), (unsigned)lrand48(),
+		       (unsigned)lrand48(), (unsigned)lrand48() % MAX_MNI);
+	if (ret < 0 || ret >= sizeof(buf)) {
+		pr_err("Can't format semaphore sysctl payload for %s\n", name);
+		close(fd);
+		return -EINVAL;
```
Comment (Snorch) [inline test/zdtm/static/ipc_namespace.c]: let's replace -EINVAL with -1, since only success/failure matters

**Review by Snorch — APPROVED** [review]
Except for a small change related to EINVAL, it looks good.

**Comment by cheese-cakee** [comment]
> Except for a small change related to EINVAL, it looks good.

thankyou I did the last two small replacements. also I have emailed you my gsoc proposal for criu , please give it a review if possible

**Comment by cheese-cakee** [comment]
hello ! Just a follow up — this PR has been reviewed and
approved , but not merged yet. Is there anything
else needed from my side before this can go in? @Snorch @avagin
