### PR TITLE
sk-inet: restore SO_BROADCAST option

### LINKED ISSUE #673: after udp restore: system call to 'sendto' report errno=EACCES Permission denied
I am experimenting with udp checkpoint feature. I have a udp client program and a udp server program. It seems to be OK by looking at the log. But when I tried to restore back to the checkpoint. The udp program failed to call `sendto`, with errno=EACCES (Permission denied). It seems the socket has lost 'SO_BROADCAST' attribute after restored.

My system configuration is as follows:
CentOS Linux release 7.1.1503 (Core)
CRIU 3.9

The following are the commands that I issued to create the problem.
criu dump -t 14455 --tcp-established --shell-job -vvvv -o dump.log && echo OK
date;criu restore -d -vvv --tcp-established --shell-job -o restore.log && echo OK

Code:
```c++
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <linux/types.h>
#include <sys/types.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <string.h>
#include <errno.h>

static int main_srv(int argc, char **argv)
{
    printf("main_srv\n");
    struct sockaddr_in cli;
    char request[400], reply[400];
    int clilen, n;
    int sk;
    sk = socket(AF_INET, SOCK_DGRAM, 0); 
    /* set reuse and non block for this socket */
    int on=1;
    setsockopt(sk, SOL_SOCKET, SO_REUSEADDR, (char *)&on, sizeof(on));
    setsockopt(sk, SOL_SOCKET, SO_BROADCAST, (char *)&on, sizeof(on));

    struct sockaddr_in servaddr; 
    memset(&servaddr, 0, sizeof(servaddr)); 
    servaddr.sin_family = AF_INET; 
    servaddr.sin_addr.s_addr = htonl(INADDR_ANY);
    servaddr.sin_port = htons(10000); 
    
    if (bind(sk, (struct sockaddr *) &servaddr, sizeof(servaddr)) != 0)
    {
          perror("Can't bind socket");
          return -1;
    }
    printf("bind to 10000\n");

    for (;;) {
        clilen = sizeof(cli);
        if ( (n=recvfrom(sk, request, 400, 0, (struct sockaddr *)&cli, &clilen)) < 0 ) {
            perror("recv from server error");
        }
        
        if ( sendto(sk, request, 400, 0, (struct sockaddr *)&cli, sizeof(cli)) != 400 ) {
            perror("sendto from server error");
        }
    }
}

static int main_cl(int argc, char **argv)
{
    printf("main_cl\n");
    char request[400], reply[400];
    int n;
    struct sockaddr_in servaddr; 
    int sk = socket(AF_INET, SOCK_DGRAM, 0); 
    if (sk < 0) {
        perror("Can't create socket");
        return -1;
    }
    /* set reuse and non block for this socket */
    int on=1;
    setsockopt(sk, SOL_SOCKET, SO_REUSEADDR, (char *)&on, sizeof(on));
    setsockopt(sk, SOL_SOCKET, SO_BROADCAST, (char *)&on, sizeof(on));

    struct sockaddr_in targetaddr; 
    memset(&targetaddr, 0, sizeof(targetaddr)); 
    targetaddr.sin_family = AF_INET; 
    //targetaddr.sin_addr.s_addr = htonl(INADDR_ANY);
    targetaddr.sin_addr.s_addr = inet_addr("127.255.255.255");
    targetaddr.sin_port = htons(10000); 

    int val = 0;
    while (1) {
        val++;
        snprintf(request, 400, "%d", val);
        if ( sendto(sk, request, 400, 0, (struct sockaddr *)&targetaddr, sizeof(targetaddr)) != 400 ) {
            perror("sendto from client error");
        }
        
        if ( (n=recvfrom(sk, reply, 400, 0, (struct sockaddr *)NULL, (int*) NULL)) < 0 ) {
            perror("recv from client error");
        }

        printf("UDP %s -> %s\n", request, reply);
        sleep(2);
    }
    
}

int main(int argc, char **argv)
{
    if (strcmp(argv[1], "server")==0 )
        return main_srv(argc, argv);
    else if (strcmp(argv[1],"client")==0 )
        return main_cl(argc, argv);

    printf("Bad usage\n");
    return 1;
}
```

### PR DESCRIPTION
**Pull request by rst0git**
Inet sockets may have broadcasting capability enabled. The `SO_BROADCAST` option is used to enable this feature. It is a Boolean flag option, which is defined, fetched, and set with the int data type. During
checkpoint, CRIU should detect the state of this flag, and during restore, it should be set appropriately.

Fixes #673

### CODE REVIEW

**Comment by 0x7f454c46** [comment]
Could you add a zdtm test for this?
I believe, the policy is to add a test for every new feature to make sure it won't be broken with some changes in future. Thanks.

File: test/zdtm/static/socket_udp-broadcast.c [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+	test_init(argc, argv);
+
+	sockfd = socket(AF_INET, SOCK_DGRAM, 0);
+	if (sockfd < 0) {
+		fail("Can't create socket");
+		return 1;
+	}
+
+	setsockopt(sockfd, SOL_SOCKET, SO_BROADCAST, &(int){ 1 }, sizeof(int));
```
Comment (avagin) [inline test/zdtm/static/socket_udp-broadcast.c]: Need to handle a return code here

File: test/zdtm/static/socket_udp-broadcast.c [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+{
+	int sockfd;
+	int val;
+	socklen_t len = sizeof(val);
+
+	test_init(argc, argv);
+
+	sockfd = socket(AF_INET, SOCK_DGRAM, 0);
+	if (sockfd < 0) {
+		fail("Can't create socket");
```
Comment (avagin) [inline test/zdtm/static/socket_udp-broadcast.c]: pr_perror()

File: test/zdtm/static/socket_udp-broadcast.c [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+		return 1;
+	}
+
+	setsockopt(sockfd, SOL_SOCKET, SO_BROADCAST, &(int){ 1 }, sizeof(int));
+
+	test_daemon();
+	test_waitsig();
+
+	getsockopt(sockfd, SOL_SOCKET, SO_BROADCAST, &val, &len);
+	if (len != sizeof(val) || val != 1) {
```
Comment (avagin) [inline test/zdtm/static/socket_udp-broadcast.c]: val can be used uninitialized here

Comment (rst0git) [reply test/zdtm/static/socket_udp-broadcast.c]: Thank you for the code review.
