### PR TITLE
sk-inet: Add support for checkpoint/restore of ICMP sockets

### LINKED ISSUE #2557: Error (criu/sk-inet.c:130): inet: Unsupported proto 1 for socket 6160e2
**Description**
My environment is Ubuntu20.04 with Docker version 27.4.0, Criu version 4.0. I tried to checkpoint a container running a command "ping www.baidu.com",  but i failed.  From the logs, it seems to be related to the ICMP protocol. When i tried to checkpoint a container running a command "tcpdump", it also failed.

**Steps to reproduce the issue:**
1. docker run -d --name base --privileged --security-opt seccomp:unconfined pure_ubuntu20 /bin/bash -c "ping www.baidu.com; tail -f /dev/null"
2. docker checkpoint create --leave-running=true base ck1

**Describe the results you received:**
root@ubuntu20:/home/ubuntu20/Workspace/Scripts# docker run -d --name base --privileged --security-opt seccomp:unconfined pure_ubuntu20 /bin/bash -c "ping www.baidu.com; tail -f /dev/null"
baea6deb367e3f341b46d5f8e40bba5fc6b250beda63fc3af5727b6276f001ea
root@ubuntu20:/home/ubuntu20/Workspace/Scripts# docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS     NAMES
baea6deb367e   pure_ubuntu20   "/bin/bash -c 'ping …"   2 seconds ago   Up 2 seconds             base
root@ubuntu20:/home/ubuntu20/Workspace/Scripts# docker checkpoint create --leave-running=true base ck1
Error response from daemon: Cannot checkpoint container base: runc did not terminate successfully: exit status 1: criu failed: type DUMP errno 0 path= /run/containerd/io.containerd.runtime.v2.task/moby/baea6deb367e3f341b46d5f8e40bba5fc6b250beda63fc3af5727b6276f001ea/criu-dump.log: unknown

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(00.049250) Error (criu/sk-inet.c:130): inet: Unsupported proto 1 for socket 6160e2
(00.049256) ----------------------------------------
(00.049268) Error (criu/cr-dump.c:1681): Dump files (pid: 1095920) failed with -1
(00.049273) Waiting for 1095920 to trap
(00.049276) Daemon 1095920 exited trapping
(00.049282) Sent msg to daemon 3 0 0
pie: 7: __fetched msg: 3 0 0
pie: 7: 7: new_sp=0x7f7e5f74c908 ip 0x7f7e5f8b76a7
(00.049322) 1095920 was trapped
(00.049334) 1095920 was trapped
(00.049338) 1095920 (native) is going to execute the syscall 15, required is 15
(00.049350) 1095920 was stopped
(00.049470) net: Unlock network
(00.049473) Running network-unlock scripts
(00.049476) 	RPC
(00.053172) Unfreezing tasks into 1
(00.053182) 	Unseizing 1095893 into 1
(00.053188) 	Unseizing 1095920 into 1
(00.053201) Error (criu/cr-dump.c:2111): Dumping FAILED.
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
root@ubuntu20:/home/ubuntu20/Workspace/Scripts# criu --version
Version: 4.0
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
root@ubuntu20:/home/ubuntu20/Workspace/Scripts# criu check --all
Warn  (criu/cr-check.c:1348): Nftables based locking requires libnftables and set concatenations support
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```
</p>
</details>

**Additional environment details:**
root@ubuntu20:/home/ubuntu20/Workspace/Scripts# uname -r
5.15.0-125-generic
root@ubuntu20:/home/ubuntu20/Workspace/Scripts# docker --version
Docker version 27.4.0, build bde2b89

### PR DESCRIPTION
**Pull request by ss141309**
Currently there is no option to checkpoint/restore programs that use ICMP sockets, such as `ping`. This patch adds support for the same.

Fixes #2557

### CODE REVIEW

**Comment by rst0git** [comment]
@ss141309 Thank you for opening this pull request! Would you be able to add a ZDTM test for this functionality?

**Comment by ss141309** [comment]
@rst0git oops, it looks like I forgot to add an IP6 version of the test, do I need to create it?

File: test/zdtm/static/socket_icmp.c [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+	close(sock);
+}
+
+int main(int argc, char **argv)
+{
+	int ret;
+	test_init(argc, argv);
+
+	test_daemon();
+	test_waitsig();
```
Comment (rst0git) [inline test/zdtm/static/socket_icmp.c:101]: @ss141309 `test_daemon()`/`test_waitsig()` should be called when the socket has been created.
The following page provides more information about the ZDTM API: https://criu.org/ZDTM_API

**Comment by rst0git** [comment]
> I forgot to add an IP6 version of the test, do I need to create it?

It would be good to have test for this. CRIU is used in some production environments where only IPv6 addresses are being used.

File: test/zdtm/static/socket_icmp.c (hunk 1 above)
Comment (rst0git) [reply test/zdtm/static/socket_icmp.c:101]: Ideally, the test should fail if the patch that adds support for ICMP sockets has not been applied.

Comment (ss141309) [reply test/zdtm/static/socket_icmp.c:101]: @rst0git do you have an idea why I am not able to create an ICMP socket in the zdtm test suite?

```c
#include "zdtmtst.h"
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip_icmp.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <netdb.h>

int main(int argc, char **argv)
{
  int sock;
  test_init(argc, argv);

  sock = socket(PF_INET, SOCK_DGRAM, IPPROTO_ICMP);
	if (sock < 0) {
		pr_perror("Can't create socket");
		return 1;
	}

	test_daemon();
	test_waitsig();

        close(sock);
	pass();
	return 0;
}
```

I run the test like this and get the output:
```
ss141309@fedora:~/criu/test$ sudo ./zdtm.py run --ignore-taint -a
[sudo] password for ss141309: 
userns is supported
The kernel is tainted: '12289'
Skipping zdtm/lib/groups (manual run only)
Skipping zdtm/static/conntracks (manual run only)
=== Run 3/3 ================ zdtm/static/socket_icmp
====================== Run zdtm/static/socket_icmp in ns =======================
 DEP       socket_icmp.d
 CC        socket_icmp.o
 LINK      socket_icmp
Start test
./socket_icmp --pidfile=socket_icmp.pid --outfile=socket_icmp.out
The test failed (0, 1)
make: *** [Makefile:504: socket_icmp.pid] Error 1
 Test zdtm/static/socket_icmp FAIL at ['make', '--no-print-directory', '-C', 'zdtm/static', 'socket_icmp.pid'] 
Test output: ================================
10:23:46.792:     4: ERR: socket_icmp.c:25: Can't create socket (errno = 13 (Permission denied))
10:23:46.792:     3: ERR: test.c:320: Test exited unexpectedly with code 1

 <<< ================================
##################################### FAIL #####################################
```

Comment (avagin) [reply test/zdtm/static/socket_icmp.c:101]: ICMP sockets probably require CAP_NET_RAW. You need to add the suid flag for this test. Here is an example: https://github.com/checkpoint-restore/criu/blob/criu-dev/test/zdtm/static/socket-raw.desc

**Comment by avagin** [comment]
As far as I remember, ICMP sockets can have attached filters and we need to dump them. Pls take a look at c2cbcaf8ac, maybe some code can be reused.

File: test/zdtm/static/socket_icmp.c (hunk 1 above)
Comment (ss141309) [reply test/zdtm/static/socket_icmp.c:101]: @avagin using ICMP protocol with SOCK_DGRAM allows it to be run rootless and without requiring CAP_NET_RAW, also even if I add an suid flag in the desc file, the test fails.

Is this a problem with my `net.ipv4.ping_group_range` variable? It is set to '0 2147483647', therefore the program should have no problem running unprivileged ICMP sockets, this is evident when I run the test manually
```
make cleanout
sudo make socket_icmp
make socket_icmp.pid
// Then C-R
make socket_icmp.out
```

The test passes with no problem

Comment (rst0git) [reply test/zdtm/static/socket_icmp.c:101]: @avagin I was also able to reproduce the error locally.

`socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP)` can be used for [non-privileged ICMP](https://manpagez.com/man/4/icmp/). This works when used outside ZDTM. However, the ZDTM environment causes `socket()` to fail with `Permission denied`.

> Is this a problem with my net.ipv4.ping_group_range variable?

The test still fails when `net.ipv4.ping_group_range` is set to `0 2147483647`

Comment (avagin) [reply test/zdtm/static/socket_icmp.c:101]: All zdtm tests are running in separate (new) network namespaces. We have two places where test  namespaces are created:
* test/zdtm_ct.c
* test/zdtm/lib/ns.c

In both cases, we need to set net.ipv4.ping_group_range.  BTW, the net.ipv4.ping_group_range sysctl value should be C/R-ed.

**Comment by ss141309** [comment]
it seems that the tests are failing because the GIDs being set. What should I set them to in the `test/zdtm_ct.c` and `test/zdtm/lib/ns.c` files? setting them to `0 2147483647` causes some of the other tests like socket_udp to fail. Also in which flavours should I run the tests?

**Comment by ss141309** [comment]
ping! @avagin @rst0git

**Comment by ss141309** [comment]
> As far as I remember, ICMP sockets can have attached filters and we need to dump them. Pls take a look at [c2cbcaf](https://github.com/checkpoint-restore/criu/commit/c2cbcaf8ac5d71844cee39087f81d6ec795eb635), maybe some code can be reused.

ICMP filters are only attached when using SOCK_RAW, since unprivileged ICMP sockets only accept ICMP_ECHO and ICMP_ECHOREPLY type messages

File: criu/sk-inet.c [hunk 2]
```diff
@@ -481,6 +482,23 @@ static int do_dump_one_inet_fd(int lfd, u32 id, const struct fd_parms *p, int fa
 			goto err;
 	}
 
+	if (type == SOCK_DGRAM && (proto == IPPROTO_ICMP || proto == IPPROTO_ICMPV6)) {
+		char buffer[16];
+
+		struct sysctl_req req[] = {
+			{ "net/ipv4/ping_group_range", &buffer, CTL_STR(16) },
```
Comment (avagin) [inline criu/sk-inet.c]: C/R of net/ipv4/ping_group_range should be in dump_netns_conf and restore_netns_conf.

**Comment by avagin** [comment]
Overall, it looks good to me. We need to move C/R of the sysctl to the proper place and resort patches. I will do all of that this week. Thanks for the contribution.

File: criu/sockets.c [hunk 3]
```diff
@@ -972,7 +972,7 @@ int collect_sockets(struct ns_id *ns)
 	req.r.i.sdiag_protocol = IPPROTO_ICMPV6;
 	req.r.i.idiag_ext = 0;
 	req.r.i.idiag_states = -1; /* All */
-	set_collect_bit(req.r.n.sdiag_family, req.r.n.sdiag_protocol);
+	set_collect_bit(req.r.i.sdiag_family, req.r.i.sdiag_protocol);
```
Comment (rst0git) [inline criu/sockets.c]: It looks like this change is not directly related to enabling checkpoint/restore of `net.ipv4.ping_group_range`.
Would you be able to move it in a separate patch?

File: criu/sockets.c [hunk 4]
```diff
@@ -926,7 +926,7 @@ int collect_sockets(struct ns_id *ns)
 	req.r.i.sdiag_protocol = IPPROTO_ICMP;
 	req.r.i.idiag_ext = 0;
 	req.r.i.idiag_states = -1; /* All */
-	set_collect_bit(req.r.i.sdiag_family, req.r.i.sdiag_protocol);
+	set_collect_bit(req.r.n.sdiag_family, req.r.n.sdiag_protocol);
```
Comment (rst0git) [inline criu/sockets.c:929]: same here... This change is applied in `zdtm: set net.ipv4.ping_group_range to 40000-50000`, but it seems unrelated.

**Comment by rst0git** [comment]
@ss141309 Would you be able update the pull request to apply the fixup changes into previous commits?
See [CONTRIBUTING.md](https://github.com/checkpoint-restore/criu/blob/criu-dev/CONTRIBUTING.md#submit-your-work-upstream) for more information.

**Comment by ss141309** [comment]
> @ss141309 Would you be able update the pull request to apply the fixup changes into previous commits? See [CONTRIBUTING.md](https://github.com/checkpoint-restore/criu/blob/criu-dev/CONTRIBUTING.md#submit-your-work-upstream) for more information.

@rst0git I did the changes, is it now alright?

**Comment by rst0git** [comment]
@ss141309 Would you be able to apply the change from `test: Actually fail and return when icmp_reply type is not ECHOREPLY` into `test: modify the IP4/ICMP test and add a test for IP6/ICMP`?

**Comment by Snorch** [comment]
> sk-inet: Checkpoint/Restore net.ipv4.ping_group_range

We need to integrate it into dump_netns_conf/restore_netns_conf, probably taking as an example https://github.com/checkpoint-restore/criu/commit/ebe3b52353c

This value belongs to namespace, not to socket.

**Comment by ss141309** [comment]
> > sk-inet: Checkpoint/Restore net.ipv4.ping_group_range
> 
> We need to integrate it into dump_netns_conf/restore_netns_conf, probably taking as an example https://github.com/checkpoint-restore/criu/commit/ebe3b52353c
> 
> This value belongs to namespace, not to socket.

Should I make a new commit or edit the existing one and force push the changes?

**Comment by Snorch** [comment]
@ss141309 I did proper handling of ping_group_range c/r here https://github.com/checkpoint-restore/criu/pull/2565, you can rebase on top of it when/if it is merged. Machinery of sysctls in CRIU is a bit too complex, I must admit. And so I helped you a bit here, as you can see there is a lot of code to do one more sysctl in the directory which is not yet handled.

File: test/zdtm/lib/ns.c [hunk 5]
```diff
@@ -332,6 +344,10 @@ int ns_init(int argc, char **argv)
 	if (create_timens())
 		exit(1);
 
+	if (set_ping_group_range() < 0) {
```
Comment (Snorch) [inline test/zdtm/lib/ns.c:347]: I believe this should not be done in generic code, please move this logic into test/zdtm/static/socket6_icmp.c the test itself.

Comment (ss141309) [reply test/zdtm/lib/ns.c:347]: @Snorch  Will #2565 be merged, when I push a fix for this? I was waiting for it to get merged first

Comment (Snorch) [reply test/zdtm/lib/ns.c:347]: Sorry for delay, I've merged it as there seems to be no objections. Please rebase on top of it.

Comment (ss141309) [reply test/zdtm/lib/ns.c]: thank you!

**Review by rst0git — APPROVED** [review]
LGTM

File: test/zdtm/static/socket_icmp.desc [hunk 6]
```diff
@@ -0,0 +1 @@
+{'flags': 'suid', 'flavor': 'h ns'}
```
Comment (avagin) [inline test/zdtm/static/socket_icmp.desc:1]: why is it suid? Why uns is excluded?

Comment (Snorch) [reply test/zdtm/static/socket_icmp.desc:1]: If we remove suid we get:
```
04:09:54.090:     4: ERR: sysctl.c:34: Can't open /proc/sys/net/ipv4/ping_group_range (errno = 13 (Permission denied))
```
Which is EACCES as file has permissions "0644", and non-root is not allowed to write it. So I believe suid is really needed.

If we add uns we get:
```
b'(00.004760)      1: Error (criu/net.c:2180): net: unix: Failed to write net/ipv4/<sysctls>'
```
I see that we get EINVAL when writing to ping_group_range on criu restore.

Likely the low/high uids we try to set got considered invalid in the userns of the caller (CRIU).

But dirty fixup to use usernsd for setting it:
```
diff --git a/criu/net.c b/criu/net.c
index ee46f1c49..5648477b0 100644
--- a/criu/net.c
+++ b/criu/net.c
@@ -2175,7 +2175,7 @@ static int ipv4_sysctls_op(SysctlEntry ***rsysctl, size_t *pn, int op)
                }
        }
 
-       ret = sysctl_op(req, n, op, CLONE_NEWNET);
+       ret = sysctl_op(req, n, op, CLONE_NEWUTS);
        if (ret < 0) {
                pr_err("unix: Failed to %s %s/<sysctls>\n", (op == CTL_READ) ? "read" : "write", IPV4_SYSCTL_BASE);
                return -1;
```

still does not fully help:
```
b'(00.041256)      4: inet: \tRestore: family AF_INET6   type SOCK_DGRAM     proto IPPROTO_ICMPV6   port 0 state TCP_CLOSE        src_addr ::'
b"(00.041372)      4: Error (criu/sk-inet.c:882): inet: Can't create inet socket: Permission denied"
```

as probably socket creation should also do socket creation from proper userns.

So it seems that we require more work to support uns flavor.

**Comment by Snorch** [comment]
It seems to me that we don't need patch "[zdtm: set net.ipv4.ping_group_range to 0-58468](https://github.com/checkpoint-restore/criu/pull/2558/commits/8d0496c3455ce0bdc42acc2378efc249746c9d02)" now as we have proper c/r of ping_group_range already, I checked that test passes without it.

File: test/zdtm/static/socket_icmp.desc (hunk 6 above)
Comment (ss141309) [reply test/zdtm/static/socket_icmp.desc]: @Snorch, was this issue fixed? If not, could you help me resolve it by providing some pointers? Do I need to use the `switch_ns` function before setting the ping_group_range, or is there another approach?

Thank you.

**Comment by yummypeng** [comment]
Hello everyone, are there any issues with this PR?

File: test/zdtm/static/socket_icmp.desc (hunk 6 above)
Comment (yummypeng) [reply test/zdtm/static/socket_icmp.desc]: This case will fail on my environment:
```
======================= Run zdtm/static/socket_icmp in h =======================
Start test
./socket_icmp --pidfile=socket_icmp.pid --outfile=socket_icmp.out
make: *** [Makefile:520: socket_icmp.pid] Error 1
 Test zdtm/static/socket_icmp FAIL at ['make', '--no-print-directory', '-C', 'zdtm/static', 'socket_icmp.pid']
Test output: ================================
11:41:44.932:    53: ERR: socket_icmp.c:38: Can't create socket (errno = 13 (Permission denied))
11:41:44.933:    52: ERR: test.c:320: Test exited unexpectedly with code 1

 <<< ================================
##################################### FAIL #####################################
```

**Comment by Snorch** [comment]
> Hello everyone, are there any issues with this PR?

Yes, there were issues: PR didn't pass its own tests =) (in host and userns flavors)

I did a small rework for ping_group_range c/r: https://github.com/checkpoint-restore/criu/pull/2679 to make it actually restore in uns flavor.

Also I updated patches 2 and 3 of this pr to fix test failures.

Let's see if it will pass all tests now, I hope it would.
